name: R Pipeline CI

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::438424052683:role/GitHubActions-ECR-customer-pipeline
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("DBI", "RPostgres", "glue", "readr", "testthat"))'

      - name: Check R script
        run: |
          Rscript -e 'parse(file = "R/pipeline.R")'

      - name: Run automated tests
        run: |
          Rscript -e 'testthat::test_dir("tests/testthat")'

      - name: Build Docker image
        run: |
          docker build -t customer-pipeline .

      - name: Smoke test Docker image
        run: |
          docker run --rm customer-pipeline \
            Rscript -e 'library(dplyr); library(DBI); library(RPostgres); library(paws.storage); library(readr)'

      - name: Tag Docker image
        run: |
          docker tag customer-pipeline:latest 438424052683.dkr.ecr.eu-north-1.amazonaws.com/kelechi-r-pipeline:${{ github.sha }}
          docker tag customer-pipeline:latest 438424052683.dkr.ecr.eu-north-1.amazonaws.com/kelechi-r-pipeline:latest

      - name: Push Docker image to ECR
        run: |
          docker push 438424052683.dkr.ecr.eu-north-1.amazonaws.com/kelechi-r-pipeline:${{ github.sha }}
          docker push 438424052683.dkr.ecr.eu-north-1.amazonaws.com/kelechi-r-pipeline:latest

      - name: Download current ECS task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition kelechi-r-pipeline-task \
            --query taskDefinition \
            > task-definition.json

      - name: Update image in ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: r-pipeline
          image: 438424052683.dkr.ecr.eu-north-1.amazonaws.com/kelechi-r-pipeline:${{ github.sha }}

      - name: Deploy and run ECS task
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          cluster: kelechi-data-engineering-cluster
          run-task: true
          run-task-launch-type: FARGATE
          run-task-subnets: subnet-0f2f36cc715c1d73d
          run-task-security-groups: sg-0505d4b5eb5639ee1
          run-task-assign-public-IP: ENABLED
          wait-for-task-stopped: true